package main

/*
	Each new term in the Fibonacci sequence is generated by adding the
	previus two terms. By starting with 1 and 2, the first 10 terms will be:
		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not
	exceed four million, find the sum of the even-valued terms.
*/

import "core:fmt"

is_even :: proc(n: int) -> bool {
	if n % 2 == 0 {
		return true
	}
	return false
}

// f(n) = f(n-1) + f(n-2)
fib :: proc(n: int) -> int {
	if n == 0 {
		return 0
	}

	if n == 1 {
		return 1
	}

	return fib(n - 1) + fib(n - 2)
}

main :: proc() {
	sum: int = 0

	for n := 0; fib(n) <= 4000000; n += 1 {
		if is_even(fib(n)) {
			sum += fib(n)
		}
	}

	fmt.printfln("The sum is: %i", sum)
}
